apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    cuahsi/description: This workflow configures a SLOTH + CFE + T-Route coupled model
      simulation using pydantic classes defined in the ngen-cal and t-route GitHub
      repositories. Configurations are created using default parameters.
    cuahsi/longname: Configure CFE for NGEN
    cuahsi/version: "0.1"
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator-email: castronova.anthony.at.gmail.com
    workflows.argoproj.io/creator-preferred-username: tonycastronova
  name: cfe-ngen-configure
  namespace: workflows
spec:
  arguments:
    parameters:
    - description: Name of the cloud bucket containing meteorological input forcing
        data.
      name: forcing-bucket
      value: acastronova
    - description: Path to the forcing directory within the 'forcing-bucket'.
      name: forcing-path
      value: wb-2853612/forcing
    - description: Name of the NetCDF file that contains meteorological forcing data.
      name: forcing-file-name
      value: results.nc
    - description: Name of the cloud bucket containing NGEN domain data.
      name: domain-bucket
      value: acastronova
    - description: Path to the domain data directory within the 'domain-bucket'.
      name: domain-path
      value: wb-2853612/domain
    - description: Name of the domain geopackage file.
      name: geopackage-file-name
      value: wb-2853612_upstream_subset.gpkg
    - description: name of the NOAH OWP attributes CSV file
      name: noaaowp-attributes-file-name
      value: cfe_noahowp_attributes.csv
    - description: Name of the cloud bucket to save output configurations to.
      name: output-bucket
      value: acastronova
    - description: Path within the 'output-bucket' to save configurations.
      name: output-path
      value: wb-2853612
  entrypoint: configure
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 600s
  templates:
  - container:
      args:
      - /srv/input/domain/{{inputs.parameters.geopackage-file-name}}
      - /srv/input/forcing/{{inputs.parameters.forcing-file-name}}
      - /srv/input/domain/{{inputs.parameters.noaaowp-attributes-file-name}}
      - /srv/output
      - "4"
      - "6"
      - --verbose
      command:
      - python
      - -u
      - entry.py
      image: cuahsi/cfe-configure:20240525
      name: ""
      ports:
      - containerPort: 8787
      resources: {}
    inputs:
      artifacts:
      - name: forcing-data
        path: /srv/input/forcing
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.forcing-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.forcing-path}}'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
      - name: domain-data
        path: /srv/input/domain
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.domain-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.domain-path}}'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
      parameters:
      - name: forcing-bucket
        value: '{{workflow.parameters.forcing-bucket}}'
      - name: forcing-path
        value: '{{workflow.parameters.forcing-path}}'
      - name: forcing-file-name
        value: '{{workflow.parameters.forcing-file-name}}'
      - name: domain-bucket
        value: '{{workflow.parameters.domain-bucket}}'
      - name: domain-path
        value: '{{workflow.parameters.domain-path}}'
      - name: geopackage-file-name
        value: '{{workflow.parameters.geopackage-file-name}}'
      - name: noaaowp-attributes-file-name
        value: '{{workflow.parameters.noaaowp-attributes-file-name}}'
      - name: output-bucket
        value: '{{workflow.parameters.output-bucket}}'
      - name: output-path
        value: '{{workflow.parameters.output-path}}'
    metadata: {}
    name: configure
    outputs:
      artifacts:
      - archive:
          none: {}
        name: output-configs
        path: /srv/output/config
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.output-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.output-path}}/config'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
      - archive:
          none: {}
        name: output-forcing
        path: /srv/output/forcing
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.output-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.output-path}}/forcing'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
