apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  creationTimestamp: "2024-01-07T06:55:03Z"
  generation: 11
  labels:
    workflows.argoproj.io/creator: "116317613255759624565"
  name: huc-to-shp
  namespace: workflows
  resourceVersion: "380125968"
  uid: 14466b94-2cb1-4960-9e51-4b4ab14c9ca2
spec:
  arguments:
    parameters:
    - name: output-path
      value: qwerty
    - name: output-bucket
      value: subsetter-outputs
    - name: hucs
      value: 102600070103,102600070104,102600090205,102600050206,102600070102
  entrypoint: huc-to-shp
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 600s
  templates:
  - container:
      args:
      - '{{inputs.parameters.hucs}}'
      - /output/watershed.shp
      image: us-central1-docker.pkg.dev/apps-320517/subsetter/huc-to-shp:0.0.4
      name: ""
      resources: {}
    inputs:
      parameters:
      - default: subsetter-outputs
        description: S3 bucket to save workflow outputs
        name: output-bucket
        value: '{{workflow.parameters.output-bucket}}'
      - default: qwerty
        description: Path within the `output-bucket` to save outputs
        name: output-path
        value: '{{workflow.parameters.output-path}}'
      - default: "102600070103"
        description: List of 12-digit HUC parameters to generate a shapefile for
        name: hucs
        value: '{{workflow.parameters.hucs}}'
    metadata:
      annotations:
        description: |
          This is a sample description
        docstring: "This is my docstring input -> value \noutput -> value\n"
    name: huc-to-shp
    outputs:
      artifacts:
      - archive:
          none: {}
        name: shape-results
        path: /output
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.output-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.output-path}}'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
