apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  labels:
    argocd.argoproj.io/instance: workflows-sync
    example: "true"
    workflows.argoproj.io/creator: "112251210534458906530"
  name: linked-ngen-metadata
  namespace: workflows
spec:
  arguments:
    parameters:
    - name: wb-id
      value: wb-2917533
    - name: vpu-id
      value: "16"
    - name: job-id
    - name: hydrofabric-url
      value: s3://nextgen-hydrofabric/pre-release/
    - name: output-bucket
      value: subsetter-outputs
    - name: output-basepath
      value: ngen
  entrypoint: subset
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: wb-id
            value: '{{workflow.parameters.wb-id}}'
          - name: vpu-id
            value: '{{workflow.parameters.vpu-id}}'
          - name: job-id
            value: '{{workflow.parameters.job-id}}'
          - name: hydrofabric-url
            value: '{{workflow.parameters.hydrofabric-url}}'
          - name: output-bucket
            value: '{{workflow.parameters.output-bucket}}'
          - name: output-basepath
            value: '{{workflow.parameters.output-basepath}}'
        name: call-ngen-subset
        templateRef:
          name: ngen-subset-v1
          template: ngen-subset-v1
      - arguments:
          parameters:
          - name: bucket
            value: '{{workflow.parameters.output-bucket}}'
          - name: path
            value: '{{workflow.parameters.output-basepath}}'
        dependencies:
        - call-ngen-subset
        name: call-metadata-extraction
        templateRef:
          name: metadata-extractor
          template: metadata-extractor
    inputs: {}
    metadata: {}
    name: subset
    outputs: {}
  workflowMetadata:
    labels:
      example: "true"
