apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    workflows.argoproj.io/creator-email: sblack.at.cuahsi.org
    workflows.argoproj.io/creator-preferred-username: sblack
  name: metadata-extractor-hydroshare
  namespace: workflows
spec:
  arguments:
    parameters:
    - name: bucket
      value: sblack-e075845338374f0893b6087f395edf45
    - name: resource-id
      value: 22c2810cae284d358e5cfcafa06c2198
  entrypoint: metadata-extractor
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 3600s
  templates:
  - container:
      args:
      - python3 hsextract/main.py extract "/files/{{inputs.parameters.resource-id}}"
        "https://dev-0.hydroshare.org/resource/{{inputs.parameters.resource-id}}/data/contents"
      command:
      - /bin/sh
      - -c
      image: scootna/hsextract:0.5.2
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: input-data
        path: /files/{{inputs.parameters.resource-id}}/
        s3:
          accessKeySecret:
            key: accessKey
            name: '{{workflow.labels.workflows.argoproj.io/creator-preferred-username}}-credentials'
          bucket: '{{inputs.parameters.bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.resource-id}}/data/contents/'
          secretKeySecret:
            key: secretKey
            name: '{{workflow.labels.workflows.argoproj.io/creator-preferred-username}}-credentials'
      parameters:
      - name: bucket
        value: '{{workflow.parameters.bucket}}'
      - name: resource-id
        value: '{{workflow.parameters.resource-id}}'
    metadata: {}
    name: metadata-extractor
    outputs:
      artifacts:
      - archive:
          none: {}
        name: output-metadata
        path: /files/{{inputs.parameters.resource-id}}/.hs/
        s3:
          accessKeySecret:
            key: accessKey
            name: '{{workflow.labels.workflows.argoproj.io/creator-preferred-username}}-credentials'
          bucket: '{{inputs.parameters.bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.resource-id}}/extracted_metadata'
          secretKeySecret:
            key: secretKey
            name: '{{workflow.labels.workflows.argoproj.io/creator-preferred-username}}-credentials'
