apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  creationTimestamp: "2024-01-07T18:32:11Z"
  generation: 28
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator: "116317613255759624565"
  name: metadata-extractor
  namespace: workflows
  resourceVersion: "636546242"
  uid: 7fef6a97-1f0c-4480-884e-ae68b1a0ce11
spec:
  arguments:
    parameters:
    - name: bucket
    - name: input-path
    - name: output-path
  entrypoint: metadata-extractor
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 3600s
  templates:
  - container:
      args:
      - python3 hsextract/main.py extract /tmp/resource
      command:
      - /bin/sh
      - -c
      image: scootna/hsextract:0.4.5
      name: ""
      resources: {}
    inputs:
      artifacts:
      - gcs:
          bucket: '{{inputs.parameters.bucket}}'
          key: '{{inputs.parameters.input-path}}'
          serviceAccountKeySecret:
            key: serviceAccountKey
            name: my-gcs-creds
        name: input-data
        path: /tmp/resource
      parameters:
      - name: bucket
        value: '{{workflow.parameters.bucket}}'
      - name: input-path
        value: '{{workflow.parameters.input-path}}'
      - name: output-path
        value: '{{workflow.parameters.output-path}}'
    metadata: {}
    name: metadata-extractor
    outputs:
      artifacts:
      - archive:
          none: {}
        gcs:
          bucket: '{{inputs.parameters.bucket}}'
          key: '{{inputs.parameters.input-path}}/.metadata'
          serviceAccountKeySecret:
            key: serviceAccountKey
            name: my-gcs-creds
        name: output-metadata
        path: /tmp/resource/.hs
