apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  labels:
    argocd.argoproj.io/instance: workflows-sync
  name: mount-example
  namespace: workflows
spec:
  arguments: {}
