apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    cuahsi/description: |
      This workflow subsets the NextGen HydroFabric for an area of interest defined by a waterbody identifier. The data that this workflow  operates on can be found at https://www.lynker-spatial.com/data?path=hydrofabric.
    cuahsi/longname: NextGen HydroFabric Subsetting
  labels:
    argocd.argoproj.io/instance: workflows-sync
    example: "true"
  name: ngen-v2.0-subset-minio
  namespace: workflows
spec:
  arguments:
    parameters:
    - description: The waterbody identification number of the most downstream catchment
        in the simulation.
      name: wb-id
      value: wb-2917533
    - description: The vector processing unit identification number associated with
        the waterbody id.
      name: vpu-id
      value: "16"
    - description: The path to the input hydrofabric datasets. in the simulation.
      name: hydrofabric-url
      value: s3://lynker-spatial/hydrofabric/v20.1/gpkg/
    - description: Path to save output data relative to the output-bucket.
      name: output-path
      value: acastronova
    - description: The name of the cloud bucket in which workflow outputs will be
        saved.
      name: output-bucket
      value: subsetter-outputs
  entrypoint: ngen-subset-v20
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 600s
  templates:
  - container:
      args:
      - '{{inputs.parameters.wb-id}}'
      - '{{inputs.parameters.vpu-id}}'
      - '{{inputs.parameters.hydrofabric-url}}'
      command:
      - python
      - -u
      - entry.py
      image: cuahsi/ngen-subset:v2.0-r1
      name: ""
      resources:
        limits:
          cpu: "2"
          ephemeral-storage: 2Gi
          memory: 4Gi
        requests:
          cpu: "1"
          ephemeral-storage: 1Gi
          memory: 1Gi
    inputs:
      parameters:
      - name: wb-id
        value: '{{workflow.parameters.wb-id}}'
      - name: vpu-id
        value: '{{workflow.parameters.vpu-id}}'
      - name: hydrofabric-url
        value: '{{workflow.parameters.hydrofabric-url}}'
      - name: output-bucket
        value: '{{workflow.parameters.output-bucket}}'
      - name: output-path
        value: '{{workflow.parameters.output-path}}'
    metadata: {}
    name: ngen-subset-v20
    outputs:
      artifacts:
      - archive:
          none: {}
        name: subset-results
        path: /srv/output
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.output-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.output-path}}/domain'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
