apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    cuahsi/description: The workflow executes an NGEN model simulation using the CIROH
      NextGen in a Box (NGIAB) service. Model simulations are executed in serial using
      the 'ngen-serial' command within the awiciroh/ciroh-ngen-image:latest-x86 docker
      image.
    cuahsi/longname: Execute NextGen in a Box (NGIAB)
    cuahsi/version: "0.1"
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator: "112251210534458906530"
  name: ngen-run
  namespace: workflows
spec:
  arguments:
    parameters:
    - description: Name of the cloud bucket that contains simulation input data.
      name: input-data-bucket
      value: acastronova
    - description: Relative path within the 'input-data-bucket' that points to the
        root simulation directory.
      name: input-data-path
      value: wb-2917533
    - description: Path relative to the 'input-data-path' pointing to the catchments.geojson
        input file.
      name: catchment-file-path
      value: domain/catchments.geojson
    - description: Path relative to the 'input-data-path' pointing to the nexus.geojson
        input file.
      name: nexus-file-path
      value: domain/nexus.geojson
    - description: Path relative to the 'input-data-path' pointing to the realization.json
        input file.
      name: realization-file-path
      value: config/realization.json
    - description: Name of the cloud bucket where simulation outputs will be saved.
      name: output-bucket
      value: acastronova
    - description: Relative path within the 'output-bucket' where simulation output
        data will be saved.
      name: output-path
      value: wb-2917533
  entrypoint: execute-ngen-simulation
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 600s
  templates:
  - inputs:
      artifacts:
      - name: input-data
        path: /ngen/data
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.input-data-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.input-data-path}}'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
      parameters:
      - name: input-data-bucket
        value: '{{workflow.parameters.input-data-bucket}}'
      - name: input-data-path
        value: '{{workflow.parameters.input-data-path}}'
      - name: catchment-file-path
        value: '{{workflow.parameters.catchment-file-path}}'
      - name: nexus-file-path
        value: '{{workflow.parameters.nexus-file-path}}'
      - name: realization-file-path
        value: '{{workflow.parameters.realization-file-path}}'
      - name: output-bucket
        value: '{{workflow.parameters.output-bucket}}'
      - name: output-path
        value: '{{workflow.parameters.output-path}}'
    metadata: {}
    name: execute-ngen-simulation
    outputs:
      artifacts:
      - archive:
          none: {}
        name: simulation-results
        path: /ngen/data/results
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.output-bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.output-path}}/results'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
    script:
      command:
      - /bin/bash
      image: awiciroh/ciroh-ngen-image:latest-x86
      name: run-ngen-simulation
      resources:
        requests:
          cpu: "2"
          ephemeral-storage: 20Gi
          memory: "16"
      source: |
        mkdir /ngen/data/results
        cd /ngen/data/;
          /dmod/bin/ngen-serial \
          /ngen/data/'{{inputs.parameters.catchment-file-path}}' all \
          /ngen/data/'{{inputs.parameters.nexus-file-path}}' all \
          /ngen/data/'{{inputs.parameters.realization-file-path}}' &&
        rm /ngen/data/results/*.parquet
