apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    cuahsi/description: This workflow subsets the National Water Model domain data
      for a specified region. The region of interest is specified as the coordinates
      of  a bounding box in the CRS of the NWM domain data.
    cuahsi/longname: Subset NWM
    cuahsi/version: "1.9"
  labels:
    argocd.argoproj.io/instance: workflows-sync
  name: nwm-subset
  namespace: workflows
spec:
  arguments:
    parameters:
    - description: NWM Model Version
      enum:
      - 1.2.4
      - 2.0.0
      - 3.0.11
      name: model-version
      value: 3.0.11
    - description: South boundary of the bounding box.
      name: y-south
      value: "-526175.60460"
    - description: West boundary of the bounding box.
      name: x-west
      value: "1339743.15750"
    - description: North boundary of the bounding box
      name: y-north
      value: "-497451.62760"
    - description: East boundary of the bounding box.
      name: x-east
      value: "1436986.49070"
    - description: Path relative to 'subsetter-outputs' to save the output files.
      name: output-path
      value: tonycastronova/nwm3
    - description: Name of the cloud bucket to save output domain data.
      name: output-bucket
      value: subsetter-outputs
    - description: Number of cells to buffer when subsetting the data (optional)
      name: cell-buffer
      value: "4"
  entrypoint: nwm-subset-with-extraction-template
  templates:
  - inputs: {}
    metadata: {}
    name: nwm-subset-with-extraction-template
    outputs: {}
    steps:
    - - arguments:
          parameters:
          - name: model-version
            value: '{{workflow.parameters.model-version}}'
          - name: output-path
            value: '{{workflow.parameters.output-path}}'
          - name: y-south
            value: '{{workflow.parameters.y-south}}'
          - name: x-west
            value: '{{workflow.parameters.x-west}}'
          - name: y-north
            value: '{{workflow.parameters.y-north}}'
          - name: x-east
            value: '{{workflow.parameters.x-east}}'
          - name: output-bucket
            value: '{{workflow.parameters.output-bucket}}'
          - name: cell-buffer
            value: '{{workflow.parameters.cell-buffer}}'
        name: nwm-subset-step-name
        template: nwm-subset-template
    - - arguments:
          parameters:
          - name: bucket
            value: '{{workflow.parameters.output-bucket}}'
          - name: input-path
            value: '{{workflow.parameters.output-path}}'
          - name: output-path
            value: '{{workflow.parameters.output-path}}_metadata.tgz'
        name: metadata-extraction
        templateRef:
          name: metadata-extractor
          template: metadata-extractor
  - container:
      args:
      - '{{inputs.parameters.y-south}}'
      - '{{inputs.parameters.x-west}}'
      - '{{inputs.parameters.y-north}}'
      - '{{inputs.parameters.x-east}}'
      - /srv/domain/nwm.v{{inputs.parameters.model-version}}/input
      - /srv/output
      - '{{inputs.parameters.cell-buffer}}'
      - '{{inputs.parameters.model-version}}'
      command:
      - python
      - -u
      - entry.py
      image: us-central1-docker.pkg.dev/apps-320517/subsetter/nwm:1.9
      name: ""
      resources: {}
      volumeMounts:
      - mountPath: /srv/domain
        name: subsetter-data-volume
    inputs:
      parameters:
      - name: model-version
      - name: y-south
      - name: x-west
      - name: y-north
      - name: x-east
      - name: output-path
      - name: output-bucket
      - name: cell-buffer
    metadata: {}
    name: nwm-subset-template
    outputs:
      artifacts:
      - gcs:
          bucket: '{{inputs.parameters.output-bucket}}'
          key: '{{inputs.parameters.output-path}}'
          serviceAccountKeySecret:
            key: serviceAccountKey
            name: my-gcs-creds
        name: subset-results
        path: /srv/output
  volumes:
  - name: subsetter-data-volume
    persistentVolumeClaim:
      claimName: subset-accelerator
