apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    cuahsi/description: This workflow subsets the National Water Model v2.0 domain
      data for a specified region. The region of interest is specified as the coordinates
      of  a bounding box in the CRS of the NWM domain data.
    cuahsi/longname: Subset NWM v2.0
    cuahsi/version: "1.0"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"WorkflowTemplate","metadata":{"annotations":{"cuahsi/description":"This workflow subsets the National Water Model v2.0 domain data for a specified region. The region of interest is specified as the coordinates of  a bounding box in the CRS of the NWM domain data.","cuahsi/longname":"Subset NWM v2.0","cuahsi/version":"1.0"},"creationTimestamp":"2024-01-25T23:21:24Z","generation":4,"labels":{"argocd.argoproj.io/instance":"workflows-sync","workflows.argoproj.io/creator":"116317613255759624565"},"name":"nwm2-subset-minio","namespace":"workflows","resourceVersion":"517372458","uid":"799bf195-05b3-4911-8564-d47b43a41d8e"},"spec":{"arguments":{"parameters":[{"description":"South boundary of the bounding box.","name":"y_south","value":"382582.18746"},{"description":"West boundary of the bounding box.","name":"x_west","value":"1720355.72762"},{"description":"North boundary of the bounding box.","name":"y_north","value":"367584.8784"},{"description":"East boundary of the bounding box.","name":"x_east","value":"1734488.4526"},{"description":"Path relative to 'subsetter-outputs' to save the output files.","name":"output-path","value":"asdf"},{"description":"Name of the cloud bucket to save output domain data.","name":"output-bucket","value":"scratch"}]},"entrypoint":"nwm2-subset-with-extraction-template","templateDefaults":{"inputs":{},"metadata":{},"outputs":{}},"templates":[{"inputs":{},"metadata":{},"name":"nwm2-subset-with-extraction-template","outputs":{},"steps":[[{"arguments":{"parameters":[{"name":"y_south","value":"{{workflow.parameters.y_south}}"},{"name":"x_west","value":"{{workflow.parameters.x_west}}"},{"name":"y_north","value":"{{workflow.parameters.y_north}}"},{"name":"x_east","value":"{{workflow.parameters.x_east}}"},{"name":"output-path","value":"{{workflow.parameters.output-path}}"},{"name":"output-bucket","value":"{{workflow.parameters.output-bucket}}"}]},"name":"nwm2-subset-step-name","template":"nwm2-subset-template"}],[{"arguments":{"parameters":[{"name":"bucket","value":"{{workflow.parameters.output-bucket}}"},{"name":"input-path","value":"{{workflow.parameters.output-path}}"},{"name":"output-path","value":"{{workflow.parameters.output-path}}_metadata.tgz"}]},"name":"metadata-extraction","templateRef":{"name":"metadata-extractor","template":"metadata-extractor"}}]]},{"container":{"args":["{{inputs.parameters.y_south}}","{{inputs.parameters.x_west}}","{{inputs.parameters.y_north}}","{{inputs.parameters.x_east}}","/srv/domain/nwm.v2.0.0/input","/srv/output"],"command":["python","-u","entry.py"],"image":"us-central1-docker.pkg.dev/apps-320517/subsetter/nwm2:0.0.1","name":"","resources":{"requests":{"cpu":"1","ephemeral-storage":"2Gi","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/srv/domain","name":"subsetter-data-volume"}]},"inputs":{"parameters":[{"name":"y_south"},{"name":"x_west"},{"name":"y_north"},{"name":"x_east"},{"name":"output-path"},{"name":"output-bucket"}]},"metadata":{},"name":"nwm2-subset-template","outputs":{"artifacts":[{"name":"subset-results","path":"/srv/output","s3":{"accessKeySecret":{"key":"accessKey","name":"minio-credentials"},"bucket":"{{inputs.parameters.output-bucket}}","endpoint":"api.minio.cuahsi.io","key":"{{inputs.parameters.output-path}}","secretKeySecret":{"key":"secretKey","name":"minio-credentials"}}}]}}],"volumes":[{"name":"subsetter-data-volume","persistentVolumeClaim":{"claimName":"subset-accelerator"}}]}}
  creationTimestamp: "2024-01-25T23:21:24Z"
  generation: 4
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator: "116317613255759624565"
  name: nwm2-subset-minio
  namespace: workflows
  resourceVersion: "629806716"
  uid: 799bf195-05b3-4911-8564-d47b43a41d8e
spec:
  arguments:
    parameters:
    - description: South boundary of the bounding box.
      name: y_south
      value: "382582.18746"
    - description: West boundary of the bounding box.
      name: x_west
      value: "1720355.72762"
    - description: North boundary of the bounding box.
      name: y_north
      value: "367584.8784"
    - description: East boundary of the bounding box.
      name: x_east
      value: "1734488.4526"
    - description: Path relative to 'subsetter-outputs' to save the output files.
      name: output-path
      value: asdf
    - description: Name of the cloud bucket to save output domain data.
      name: output-bucket
      value: scratch
  entrypoint: nwm2-subset-with-extraction-template
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
  templates:
  - inputs: {}
    metadata: {}
    name: nwm2-subset-with-extraction-template
    outputs: {}
    steps:
    - - arguments:
          parameters:
          - name: y_south
            value: '{{workflow.parameters.y_south}}'
          - name: x_west
            value: '{{workflow.parameters.x_west}}'
          - name: y_north
            value: '{{workflow.parameters.y_north}}'
          - name: x_east
            value: '{{workflow.parameters.x_east}}'
          - name: output-path
            value: '{{workflow.parameters.output-path}}'
          - name: output-bucket
            value: '{{workflow.parameters.output-bucket}}'
        name: nwm2-subset-step-name
        template: nwm2-subset-template
    - - arguments:
          parameters:
          - name: bucket
            value: '{{workflow.parameters.output-bucket}}'
          - name: input-path
            value: '{{workflow.parameters.output-path}}'
          - name: output-path
            value: '{{workflow.parameters.output-path}}_metadata.tgz'
        name: metadata-extraction
        templateRef:
          name: metadata-extractor
          template: metadata-extractor
  - container:
      args:
      - '{{inputs.parameters.y_south}}'
      - '{{inputs.parameters.x_west}}'
      - '{{inputs.parameters.y_north}}'
      - '{{inputs.parameters.x_east}}'
      - /srv/domain/nwm.v2.0.0/input
      - /srv/output
      command:
      - python
      - -u
      - entry.py
      image: us-central1-docker.pkg.dev/apps-320517/subsetter/nwm2:0.0.1
      name: ""
      resources:
        requests:
          cpu: "1"
          ephemeral-storage: 2Gi
          memory: 1Gi
      volumeMounts:
      - mountPath: /srv/domain
        name: subsetter-data-volume
    inputs:
      parameters:
      - name: y_south
      - name: x_west
      - name: y_north
      - name: x_east
      - name: output-path
      - name: output-bucket
    metadata: {}
    name: nwm2-subset-template
    outputs:
      artifacts:
      - name: subset-results
        path: /srv/output
        gcs:
          serviceAccountKeySecret:
            key: serviceAccountKey
            name: my-gcs-creds
          bucket: '{{inputs.parameters.output-bucket}}'
          key: '{{inputs.parameters.output-path}}'
  volumes:
  - name: subsetter-data-volume
    persistentVolumeClaim:
      claimName: subset-accelerator
