apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: simple-test
  name: serenity-now
  namespace: workflows
spec:
  arguments:
    parameters:
    - name: inputPath
      value: foobarbaz/test/abc
  entrypoint: whalesay
  templates:
  - container:
      args:
      - '{{inputs.parameters.inputFolder}}'
      command:
      - cowsay
      image: docker/whalesay
      name: whalesay
      resources: {}
    inputs:
      parameters:
      - name: inputpath
        value: '{{workflow.parameters.inputPath}}'
      - name: inputFolder
        value: '{{=sprig.base(workflow.parameters.inputPath)}}'
    metadata: {}
    name: whalesay
    outputs: {}
