apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  generateName: simple-test
  labels:
    argocd.argoproj.io/instance: workflows-sync
  name: serenity-now
  namespace: workflows
spec:
  arguments: {}
  entrypoint: whalesay
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  templates:
  - container:
      args:
      - ls /tmp/data | cowsay
      command:
      - sh
      - -c
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - gcs:
          bucket: subsetter-static-input
          key: nwm.v1.2.4
          serviceAccountKeySecret:
            key: serviceAccountKey
            name: my-gcs-creds
        name: input-data
        path: /tmp/data
    metadata: {}
    name: whalesay
    outputs: {}
