apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  labels:
    argocd.argoproj.io/instance: workflows-sync
  name: subsetter-dataset-pvc
  namespace: workflows
spec:
  arguments: {}
  entrypoint: generate-volume
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 3600s
  templates:
  - inputs: {}
    metadata: {}
    name: generate-volume
    outputs:
      parameters:
      - name: pvc-name
        valueFrom:
          jsonPath: '{.metadata.name}'
    resource:
      action: create
      manifest: "apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  generateName:
        subsetter-dataset-pvc-\nspec:\n  storageClassName: manual\n  accessModes:
        \n  - ReadOnlyMany\n  resources:\n    requests:\n      storage: 20Gi\n"
      setOwnerReference: true
