apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"WorkflowTemplate","metadata":{"annotations":{},"creationTimestamp":"2024-01-18T02:44:12Z","generation":3,"labels":{"argocd.argoproj.io/instance":"workflows-sync","workflows.argoproj.io/creator":"116317613255759624565"},"name":"subsetter-dataset-pvc","namespace":"workflows","resourceVersion":"629806703","uid":"8c6de0ec-5177-47e9-a3b8-60ec40a1c866"},"spec":{"arguments":{},"entrypoint":"generate-volume","templateDefaults":{"inputs":{},"metadata":{},"outputs":{},"retryStrategy":{"limit":"0"},"timeout":"3600s"},"templates":[{"inputs":{},"metadata":{},"name":"generate-volume","outputs":{"parameters":[{"name":"pvc-name","valueFrom":{"jsonPath":"{.metadata.name}"}}]},"resource":{"action":"create","manifest":"apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  generateName: subsetter-dataset-pvc-\nspec:\n  storageClassName: manual\n  accessModes: \n  - ReadOnlyMany\n  resources:\n    requests:\n      storage: 20Gi\n","setOwnerReference":true}}]}}
  creationTimestamp: "2024-01-18T02:44:12Z"
  generation: 3
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator: "116317613255759624565"
  name: subsetter-dataset-pvc
  namespace: workflows
  resourceVersion: "636518007"
  uid: 8c6de0ec-5177-47e9-a3b8-60ec40a1c866
spec:
  arguments: {}
  entrypoint: generate-volume
  templateDefaults:
    inputs: {}
    metadata: {}
    outputs: {}
    retryStrategy:
      limit: "0"
    timeout: 3600s
  templates:
  - inputs: {}
    metadata: {}
    name: generate-volume
    outputs:
      parameters:
      - name: pvc-name
        valueFrom:
          jsonPath: '{.metadata.name}'
    resource:
      action: create
      manifest: "apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  generateName:
        subsetter-dataset-pvc-\nspec:\n  storageClassName: manual\n  accessModes:
        \n  - ReadOnlyMany\n  resources:\n    requests:\n      storage: 20Gi\n"
      setOwnerReference: true
