apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  creationTimestamp: "2023-07-18T13:54:41Z"
  generateName: test-input-artifacts-
  generation: 5
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator: "112251210534458906530"
  name: test-input-artifacts
  namespace: workflows
  uid: 19bfb17a-80bb-4949-b830-d52ac6105547
spec:
  arguments:
    parameters:
    - name: bucket
    - name: folder
    - name: output_bucket
    - name: output_folder
  entrypoint: whalesay
  templates:
  - container:
      args:
      - ls /tmp/data | cowsay
      command:
      - sh
      - -c
      image: docker/whalesay:latest
      name: ""
      resources:
        requests:
          cpu: "2"
          memory: 8Gi
    inputs:
      artifacts:
      - name: input-data
        path: /tmp/data
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.folder}}'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
      parameters:
      - name: bucket
      - name: folder
      - name: output_bucket
      - name: output_folder
    metadata: {}
    name: whalesay
    outputs:
      artifacts:
      - name: output-data
        path: /tmp/data
        s3:
          accessKeySecret:
            key: accessKey
            name: minio-credentials
          bucket: '{{inputs.parameters.output_bucket}}'
          endpoint: api.minio.cuahsi.io
          key: '{{inputs.parameters.output_folder}}'
          secretKeySecret:
            key: secretKey
            name: minio-credentials
