apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
  generateName: test-dask-
  labels:
    argocd.argoproj.io/instance: workflows-sync
    workflows.argoproj.io/creator: "112251210534458906530"
  name: test-dask
  namespace: workflows
spec:
  arguments: {}
  entrypoint: dask-test-script
  templates:
  - inputs: {}
    metadata: {}
    name: dask-test-script
    outputs: {}
    script:
      command:
      - python
      image: ghcr.io/dask/dask
      name: main
      ports:
      - containerPort: 8787
      resources:
        requests:
          cpu: "2"
          ephemeral-storage: 10Gi
          memory: 6Gi
      source: |
        import dask.bag as db
        from operator import add
        from dask.distributed import Client, progress

        if __name__ == "__main__":
          client = Client(n_workers=3, memory_limit='2GB')
          print(client)

          b = db.from_sequence(range(0, 5000), npartitions=1)
          res = b.map(add, b).compute()
          print(sum(res))
  ttlStrategy:
    secondsAfterCompletion: 300
  workflowMetadata:
    labels:
      example: "true"
